### ISSUE TITLE
Getting an Build error

### ISSUE THREAD

**Issue by ghost** [johnBuffer/ClothSimulation#3]
Heyo, first of all, thanks for the help ;D
second of all, i have no clue if its because of the code, which it is apparently but i get an error (or better two) when i build it

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2398	Element '1': conversion from 'const int32_t' to 'T' requires a narrowing conversion
Error	C2398	Element '2': conversion from 'const int32_t' to 'T' requires a narrowing conversion	
	
Both in Line 31 from main.cpp

**Comment by johnBuffer** [comment]
Yes it seems it is coming from the code, I will look into this.

**Comment by ghost** [comment]
Did you already change it?
i see, that you changed something at main.cpp, and wasnt sure if you already change something in the code.

If not, then its totally okey xD, just wanted to ask

**Comment by johnBuffer** [comment]
The change is not related to the issue, you should have the same. Can you confirm to me that you still have it and at which line ? I think it should be at the creation of the window context but I am not sure

**Comment by ghost** [comment]
Like i said  its from line 31 in main.cpp
And yeah it is indeed the line with the window.

**Comment by johnBuffer** [comment]
I asked for the line because it seems to be an older version of the main file. I did push a fix, can you tell me if it is compiling now ?

**Comment by ghost** [comment]
Oh god, there are now even more xD
![Bild_2021-09-03_134424](https://user-images.githubusercontent.com/74104789/132000025-2e36162c-929d-488b-8640-8c1d2d83c7a9.png)

**Comment by ghost** [comment]
I am so sorry, for bothering you with this that much.

**Comment by johnBuffer** [comment]
No problem, I am programming on mac os so it is possible that things are not working that well on other systems. I will try to see 
if I can reproduce on visual studio

**Comment by johnBuffer** [comment]
With the latest commit I was able to compile it with visual studio 2019, let me know if you have issues

**Comment by ghost** [comment]
Yes it works :D 
(Maybe with some workarounds, but this doesnt have sth to do with the code anymore)

Thank you so much for helping!

**Comment by johnBuffer** [comment]
No problem, thanks to you it compiles on visual studio now 😃
